### ISSUE TITLE
Идеи:

### ISSUE THREAD

**Issue by LightVolk** [Aecid/Chatcraft#5]
Есть идея распилить сборку на несколько. Одна из них должна содержать код с логикой,остальные- порты под .net core,windows и тд.
И , возможно, отдельные АПИ для других мессенджеров.

**Comment by Aecid** [comment]
В целом звучит логично.

Только, боюсь, в ближайший месяц у меня не будет шансов поработать над ботом, на работе завал страшный.

**Comment by LightVolk** [comment]
Если будет время у меня- попробую частично реализовать. А то завалы тоже могут быть внезапными

**Comment by LightVolk** [comment]
Распилил на 2 сборки. Думаю, на этом с распилом можно закончить на данный момент.
